export const overview = {
  zh: {
    lang: "zh-Hans", other: "English", nav: ["研究", "进展", "支持"],
    title: "K4 Cell Framework · 从四个点，追问自然的结构",
    eyebrow: "梁植华 · K4 Cell Framework",
    headline: "从四个点，<br>追问自然的结构。",
    lead: "K4 正尝试从一个有限量子结构出发，推导自然界的结构与参数。专著 v3.0 正在编写；公开材料、推导边界和未完成的问题，都从这里进入。",
    read: "读研究", support: "支持研究", status: "v3.0 编写中", date: "进展更新 · 2026-09-09",
    figure: "K4 完全图：四个顶点，两两相连，共六条边。图示表达研究对象，不是宇宙观测图像。",
    introTitle: "先认识研究对象。",
    intro: "四个点，两两相连，构成 K4 完全图。框架从有限的局部结构出发，研究更大的物理结构能否由此导出。关键不只是数值是否接近，还包括推导是否成立，以及从有限系统通向物理世界的条件能否兑现。",
    detailTitle: "公式、数值与物理结论，分别核对",
    detail: "已发表的数值比较、条件性推导与尚待解决的桥接问题，在深读页中分开列出。一个具体检验若失败，应更新它所约束的主张和依赖链，不自动宣布所有独立结果失效。",
    deep: "进入完整介绍与核对工具 →",
    progressTitle: "研究正在推进。",
    progressCards: [
      ["01 / 已公开", "v2.0 公开审阅版", "2026-07-08 冻结的专著仍可阅读。勘误与审阅靶点单独维护，方便读者核对具体问题。", "读公开专著"],
      ["02 / 进行中", "v3.0 专著升级", "作者确认正在编写和升级。新版本尚未作为公开 PDF 发布，完成后会有独立版本和核对信息。", "查看进展"],
      ["03 / 待推进", "预测与独立检验", "预测登记基础已公开；目前没有已登记的预注册预测。后续需要把具体主张、适用条件与观测量逐项对应。", "查看登记状态"],
    ],
    papersTitle: "论文、版本与证据。",
    papers: [
      ["公开专著", "v2.0 · 冻结版", "PDF 与版本身份"],
      ["修订与审阅", "勘误 / 审阅靶点", "读者可从具体问题开始"],
      ["数值与推导", "完整研究介绍", "比较、假设和未完成的桥接"],
      ["在建版本", "v3.0 · 编写中", "进度不等于已发布或已获验证"],
    ],
    participateTitle: "选择你想参与的方式。",
    participate: [
      ["关注研究", "阅读材料，或来信表达想了解的研究进展。", "研究与更新"],
      ["资助 / 合作", "讨论专著整理、可复现材料或独立审查等具体工作。", "讨论支持方式"],
      ["了解 K4V", "阅读尚未发行的代币方案，说明你的条件和顾虑。", "看说明与问卷"],
    ],
    footer: "K4 是尚未获得独立确立的候选理论。支持研究、市场关注和代币价格都不能证明理论正确。",
    noMint: "K4V 尚未发行", official: "核对官方签名声明", home: "返回首页", language: "语言",
    progressHeading: "公开版本与正在做的事",
    progressNote: "本页区分已公开工件与作者报告的在建进展。最后更新：2026-09-09。",
    progressRows: [
      ["2026-07-08", "v2.0 公开冻结", "公开 PDF 保持原样；后续勘误不会静默替换已冻结文本。"],
      ["2026-08-29", "公开审阅与登记材料", "勘误、审阅靶点及预测登记基础可核对。登记表目前为空，不把历史数值吻合列为预注册预测。"],
      ["2026-09-09", "v3.0 编写中", "根据作者本次确认更新。尚无 v3.0 公开 PDF；未公开的推导不作为本页已核验成果。"],
    ],
    journalNote: "拆出论文的期刊状态见公开审阅记录；记录日期与专著版本分开标注。专著本身不等于已通过期刊审稿。",
    supportHeading: "让下一项研究工作得以完成。",
    supportLead: "你可以先讨论一个具体工作包的范围、交付物和预算。现在通过邮件联系；本页没有付款入口。",
    workHeading: "可以讨论的工作包",
    work: [
      ["专著与论文整理", "v3.0 的版本梳理、推导表述与公开材料导航。"],
      ["可复现材料", "把选定结论需要的代码、输入和验证说明整理为可复核工件。"],
      ["关键推导", "围绕一个明确问题安排作者研究时间，并记录条件与未完成部分。"],
      ["独立审查", "按明确范围讨论评审人、报价与交付物；不以正面结论为付费条件。"],
    ],
    workNote: "具体费用与里程碑在范围明确后讨论。个人、机构与技术合作都可以从一个问题开始。联系不会产生股权、代币分配或收益权。",
    supportCta: "打开合作邮件草稿", mailNote: "请在邮件应用中检查并发送。打开草稿不代表已经联系成功。",
    updatesCta: "打开研究更新邮件草稿", updatesNote: "请写明想了解的主题与是否愿意接收后续更新；联系本身不会自动订阅。",
    interestHeading: "先读方案，再说你的判断。",
    interestLead: "这是早期意见征集，用来找出理解偏差、购买条件和拒绝原因。不是预售、白名单、订单或收益承诺。",
    proposalLabel: "实施候选 · K4V-180D-2026-09-09",
    terms: [
      ["定位", "与 K4 及作者未来可能获得的关注相关的纯 meme 方案。持币不附带股权、IP、分红或科学投票权。"],
      ["供应与分配", "总量 10 亿；创始人 30%、研究国库 50%、首发 12%、流动性 8%。"],
      ["个人释放", "发行时可售为零。候选为从官方发行起点锁定 180 天（约六个月），此后按 30 天周期限额释放；不全额解锁、不补发、不结转。"],
      ["研究国库", "发行时可售为零；没有个人锁定期，后续受研究预算、公告、单池与两池合计额度约束。"],
      ["还未确定", "价格、估值、流动性及部分发行参数尚未冻结。现有公开金库程序仍是 730 天版本；180 天新程序尚未验收。研究也可能失败。"],
    ],
    questions: ["你关注它的主要原因是什么？也可以说没有兴趣。", "用自己的话说：你认为持币会得到什么？", "在没有收益承诺、研究也可能失败的前提下，你更接近哪种情况？", "什么条件最影响你的判断？", "什么会让你明确不买？", "条款完善后，你是否愿意再看一次？"],
    interests: ["不考虑", "愿意了解", "满足条件后可能少量购买", "倾向参与"],
    choose: "请选择", revisit: ["愿意", "不愿意", "暂不确定"],
    optionalContact: "希望使用的联系方式（可选）", optionalChannel: "从哪里了解到本项目？（可选）",
    consent: "我同意就这份方案收到一次后续联系（可选）。",
    privacy: "答案只会放进你检查后自行发送的邮件。页面不上传或保存回答。来信地址会随邮件提供；填写联系方式不等于同意跟进。可以回复“停止”取消后续联系。",
    prepare: "生成邮件草稿", preview: "检查草稿", send: "在邮件应用中打开", fallback: "也可以直接来信", fallbackNote: "若邮件应用无法打开，请复制草稿，发送至 zhihua@k4cell.com。",
    noscript: "启用 JavaScript 可生成结构化草稿；也可直接来信，按上面六题写下回答。",
    prepared: "草稿已生成，尚未发送。请检查后在邮件应用中发送。",
  },
  en: {
    lang: "en", other: "简体中文", nav: ["Research", "Progress", "Support"],
    title: "K4 Cell Framework · Asking about nature, starting with four points",
    eyebrow: "Zhihua Liang · K4 Cell Framework",
    headline: "Asking about nature.<br>Starting with four points.",
    lead: "K4 explores whether a finite quantum structure can lead to the structures and parameters of nature. Monograph v3.0 is in progress. Start here for the public work, its assumptions, and the questions still open.",
    read: "Read the research", support: "Support the work", status: "v3.0 in progress", date: "Progress updated · 2026-09-09",
    figure: "The complete graph K4: four vertices joined by six edges. This depicts the research object, not an observation of the universe.",
    introTitle: "Start with the object.",
    intro: "Four points, each connected to every other point, make the complete graph K4. The framework asks whether larger physical structures can follow from a finite local starting point. Numerical agreement matters, but so do the derivations and the conditions connecting a finite system to the physical world.",
    detailTitle: "Check formulas, numbers, and physical claims separately",
    detail: "The full research page separates published comparisons, conditional derivations, and open bridges. A failed test should update the claim it constrains and its dependencies; it does not automatically invalidate every independent result.",
    deep: "Explore the full account and checking tools →",
    progressTitle: "Work in progress.",
    progressCards: [
      ["01 / PUBLIC", "v2.0 public review", "The monograph frozen on 8 July 2026 remains available. Errata and review targets are maintained separately so readers can inspect specific questions.", "Read the public monograph"],
      ["02 / IN PROGRESS", "Monograph v3.0", "The author confirms that writing and revision are underway. A public v3.0 PDF has not been released; it will need its own version identity and checksums.", "See progress"],
      ["03 / NEXT", "Predictions and independent tests", "The registry foundation is public, with no preregistered entries yet. Specific claims, conditions, and observables still need to be mapped together.", "Check the registry"],
    ],
    papersTitle: "Papers, versions, and evidence.",
    papers: [
      ["Public monograph", "v2.0 · frozen", "PDF and version identity"],
      ["Revision and review", "Errata / review targets", "Start with a specific question"],
      ["Numbers and derivations", "Full research account", "Comparisons, assumptions, and open bridges"],
      ["Working version", "v3.0 · in progress", "Progress is not publication or verification"],
    ],
    participateTitle: "Choose how to take part.",
    participate: [
      ["Follow the research", "Read the work or write about the developments you would like to follow.", "Research and updates"],
      ["Funding / collaboration", "Discuss a defined piece of work: the monograph, reproducibility materials, or independent review.", "Discuss support"],
      ["Learn about K4V", "Read the unlaunched token proposal and explain your conditions and concerns.", "Proposal and questions"],
    ],
    footer: "K4 is a candidate framework that is not independently established. Funding, attention, and token prices cannot establish whether its scientific claims are true.",
    noMint: "K4V has not launched", official: "Verify the signed official statement", home: "Back to the homepage", language: "Language",
    progressHeading: "Public versions and ongoing work",
    progressNote: "Published artifacts and author-reported work in progress are identified separately. Last updated: 2026-09-09.",
    progressRows: [
      ["2026-07-08", "v2.0 public freeze", "The public PDF remains unchanged. Later errata do not silently replace the frozen text."],
      ["2026-08-29", "Review and registry materials", "Errata, review targets, and the prediction registry foundation can be inspected. The registry is currently empty; historical numerical matches are not preregistered predictions."],
      ["2026-09-09", "v3.0 in progress", "Updated from the author’s confirmation. There is no public v3.0 PDF yet; unpublished derivations are not presented here as verified results."],
    ],
    journalNote: "See the public review record for carved-paper journal status. The record date and monograph version are distinct. The monograph itself has not passed journal peer review.",
    supportHeading: "Help the next piece of research happen.",
    supportLead: "Start by discussing a defined work package, its outputs, and its budget. Contact is by email for now; this page does not accept payments.",
    workHeading: "Possible work packages",
    work: [
      ["Monograph and papers", "Version organization, exposition of derivations, and navigation for the v3.0 work."],
      ["Reproducibility materials", "Code, inputs, and verification instructions for a selected result."],
      ["A focused derivation", "Author research time for a named question, with assumptions and remaining gaps recorded."],
      ["Independent review", "A defined scope, reviewer, quote, and deliverable; payment does not depend on a positive conclusion."],
    ],
    workNote: "Costs and milestones follow an agreed scope. Individuals, institutions, and technical collaborators can begin with one question. Contact grants no equity, token allocation, or right to returns.",
    supportCta: "Open a collaboration email draft", mailNote: "Review and send in your email app. Opening a draft does not mean a message has been received.",
    updatesCta: "Open a research updates email draft", updatesNote: "Describe the topic you want to follow and whether you want further updates. Contact does not automatically subscribe you.",
    interestHeading: "Read the proposal. Tell us what you think.",
    interestLead: "These early questions help identify misunderstandings, conditions, and reasons to decline. This is not a presale, whitelist, order, or promise of returns.",
    proposalLabel: "Implementation candidate · K4V-180D-2026-09-09",
    terms: [
      ["Thesis", "A pure meme proposal connected to possible future attention around K4 and its author. Holding it provides no equity, IP, dividends, or scientific voting rights."],
      ["Supply and allocation", "One billion tokens: founder 30%, research treasury 50%, genesis 12%, liquidity 8%."],
      ["Founder release", "Zero sellable at launch. The candidate locks the founder pool for 180 days (about six months) from official launch, followed by capped 30-day windows. No full unlock, catch-up, or quota carryover."],
      ["Research treasury", "Zero sellable at launch; no founder cliff. Later releases require research budgets, notice, per-vault limits, and a shared market-capacity limit."],
      ["Still open", "Price, valuation, liquidity, and some launch parameters are not frozen. Published vault programs still use 730 days; a new 180-day program has not passed acceptance. The research may fail."],
    ],
    questions: ["What draws your attention? No interest is a valid answer.", "In your own words, what do you think holding the token would provide?", "With no promised return, and research that may fail, which best describes you?", "Which conditions matter most to your decision?", "What would make you definitely decline?", "Would you look again after the terms are more complete?"],
    interests: ["Would not consider", "Would like to learn", "Might buy a small amount if conditions are met", "Inclined to participate"],
    choose: "Choose an answer", revisit: ["Yes", "No", "Unsure"],
    optionalContact: "Preferred contact details (optional)", optionalChannel: "Where did you hear about this project? (optional)",
    consent: "I agree to one follow-up about this proposal (optional).",
    privacy: "Answers go only into an email you review and send yourself. This page does not upload or save responses. Your sender address accompanies the email; providing contact details does not give follow-up consent. Reply ‘stop’ to withdraw from further contact.",
    prepare: "Prepare email draft", preview: "Review the draft", send: "Open in your email app", fallback: "You can also write directly", fallbackNote: "If your email app does not open, copy the draft and send it to zhihua@k4cell.com.",
    noscript: "Enable JavaScript to prepare a structured draft, or email your answers to the six questions above.",
    prepared: "Draft prepared; nothing has been sent. Review it, then send from your email app.",
  },
};
